-- Create a table named person
CREATE TABLE IF NOT EXISTS person (
    id serial PRIMARY KEY,
    fullName VARCHAR NOT NULL UNIQUE,
    isDeleted  BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00',
    deletedAt TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00'
);